# Generated by Django 4.1.1 on 2023-09-16 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostMainHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(default='')),
                ('balance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankInformation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('account_no', models.CharField(max_length=150, unique=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(max_length=150)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.CreateModel(
            name='LoanInformation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('borrower_name', models.CharField(max_length=150)),
                ('loan_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('due', 'Due')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=150, null=True)),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.CreateModel(
            name='ProjectSiteEngineer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_engineer', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.CreateModel(
            name='CostSubHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='')),
                ('balance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_head', to='tender.costmainhead')),
            ],
        ),
        migrations.CreateModel(
            name='TenderProject',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('project_name', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('job_no', models.CharField(blank=True, max_length=200, null=True)),
                ('project_location', models.CharField(max_length=200)),
                ('procuring_entity_name', models.CharField(max_length=200)),
                ('contact_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_infrastructure', models.PositiveIntegerField()),
                ('infrastructure_description', models.TextField()),
                ('project_complete', models.BooleanField(default=False)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tender_project', to='tender.projectsiteengineer')),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.CreateModel(
            name='TenderPg',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('pg_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_withdraw', models.BooleanField(default=False)),
                ('maturity_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tender.tenderproject')),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.CreateModel(
            name='SecurityMoney',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_withdraw', models.BooleanField(default=False)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('tender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tender.tenderproject')),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.CreateModel(
            name='RetensionMoney',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_withdraw', models.BooleanField(default=False)),
                ('maturity_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.tenderproject')),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.CreateModel(
            name='MoneyReceived',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('received_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('recieved_cheque_no', models.CharField(blank=True, max_length=150, null=True)),
                ('recieved_bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('check_attachment', models.FileField(blank=True, null=True, upload_to='check_attachment/')),
                ('deduction_of_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('deduction_of_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('deduction_of_ld', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('misc_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('security_money', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=13)),
                ('bank_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_money_received', to='tender.bankinformation')),
                ('cash_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_received', to='tender.cashbalance')),
                ('loan_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_received', to='tender.loaninformation')),
                ('performance_gurantee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pg_received', to='tender.tenderpg')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_money_received', to='tender.tenderproject')),
                ('retention_money', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tender.retensionmoney')),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.CreateModel(
            name='DailyExpendiature',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('due', 'Due')], max_length=30)),
                ('expendiature_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_expendiature', to='tender.bankinformation')),
                ('cash_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_expendiature', to='tender.cashbalance')),
                ('loan_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_expendiature', to='tender.loaninformation')),
                ('main_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_head_expendiature', to='tender.costmainhead')),
                ('performance_gurantee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pg_expendiature', to='tender.tenderpg')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_expendiature', to='tender.tenderproject')),
                ('security_money', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_money_expendiature', to='tender.securitymoney')),
                ('site_engier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_engier_expendiature', to='tender.projectsiteengineer')),
                ('sub_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_head_expendiature', to='tender.costsubhead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('tender.basemodel',),
        ),
    ]
