# Generated by Django 4.1.1 on 2023-05-06 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInformation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('account_no', models.CharField(max_length=150, unique=True)),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(max_length=150)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.CreateModel(
            name='ProjectSiteEngineer',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_engineer', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.RenameField(
            model_name='dailyexpendiature',
            old_name='deposit_account_no',
            new_name='cheque_no',
        ),
        migrations.RemoveField(
            model_name='dailyexpendiature',
            name='deposit_bank_name',
        ),
        migrations.RemoveField(
            model_name='dailyexpendiature',
            name='deposit_branch_name',
        ),
        migrations.RemoveField(
            model_name='dailyexpendiature',
            name='issue_bank_name',
        ),
        migrations.RemoveField(
            model_name='dailyexpendiature',
            name='issue_cheque_no',
        ),
        migrations.CreateModel(
            name='SiteEngineerPayments',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField()),
                ('paid_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('due', 'Due')], max_length=30)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_engineer_pay', to='tender.projectsiteengineer')),
            ],
            bases=('tender.basemodel',),
        ),
        migrations.AddField(
            model_name='dailyexpendiature',
            name='bank_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_expendiature', to='tender.bankinformation'),
        ),
    ]
