# Generated by Django 4.1.1 on 2024-01-20 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyreceived',
            name='tender_security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='security_money_received', to='tender.securitymoney'),
        ),
    ]
