# Generated by Django 4.1.1 on 2023-05-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_bankinformation_projectsiteengineer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderproject',
            name='engineer',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, related_name='tender_project', to='tender.projectsiteengineer'),
            preserve_default=False,
        ),
    ]
