# Generated by Django 4.1.1 on 2024-01-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_moneyreceived_tender_security'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securitymoney',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='moneyreceived',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_money_received', to='tender.tenderproject'),
        ),
    ]
