# Generated by Django 5.0.3 on 2024-03-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_alter_securitymoney_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenderpg',
            options={'ordering': ('-created_at',)},
        ),
    ]
