# Generated by Django 3.2.21 on 2024-03-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_alter_securitymoney_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenderpg',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='loaninformation',
            name='account_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='loaninformation',
            name='payment_option',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('due', 'Due')], default='bank', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loaninformation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitymoney',
            name='bank_details',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='securitymoney',
            name='security_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('pay_order', 'Pay Order')], default='bank', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenderpg',
            name='bank_details',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='loaninformation',
            name='bank_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='loaninformation',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loaninformation',
            name='loan_type',
            field=models.CharField(choices=[('pay', 'Pay'), ('receive', 'Received'), ('collection', 'Collection')], max_length=20),
        ),
    ]
