# Generated by Django 3.2.21 on 2024-03-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_auto_20240306_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyreceived',
            name='account_no',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
