# Generated by Django 3.2.21 on 2024-03-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0006_moneyreceived_loan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaninformation',
            name='loan_type',
        ),
    ]
