# Generated by Django 3.2.21 on 2024-03-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0007_remove_loaninformation_loan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyexpendiature',
            name='expendiature_type',
        ),
    ]
