# Generated by Django 3.2.21 on 2024-03-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_alter_tenderpg_options'),
        ('tender', '0008_remove_dailyexpendiature_expendiature_type'),
    ]

    operations = [
    ]
