# Generated by Django 5.0.3 on 2024-03-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0009_merge_20240306_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitymoney',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderpg',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
