# Generated by Django 5.0.3 on 2024-03-12 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0010_alter_securitymoney_bank_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderpg',
            name='pg_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('pay_order', 'Pay Order')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tender.basemodel')),
                ('profile_img', models.ImageField(default='profile_img/default.jpg', upload_to='profile_img/')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('nid_no', models.CharField(max_length=100, unique=True)),
                ('phone_no', models.CharField(max_length=100)),
                ('religion', models.CharField(choices=[('ISLAM', 'Islam'), ('HINDU', 'Hindu'), ('CHRISTIAN', 'Christian'), ('BUDDHIST', 'Buddhist'), ('OTHERS', 'Others')], max_length=20)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('DIVORCED', 'Divorced')], max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHERS', 'Others')], max_length=15)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=15)),
                ('date_of_birth', models.DateField()),
                ('date_of_join', models.DateField()),
                ('address', models.TextField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('tender.basemodel',),
        ),
    ]
