# Generated by Django 5.0.3 on 2024-03-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0011_alter_tenderpg_pg_type_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loaninformation',
            old_name='remarks',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='loaninformation',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='loaninformation',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='loaninformation',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='loaninformation',
            name='cheque_no',
        ),
        migrations.RemoveField(
            model_name='loaninformation',
            name='payment_option',
        ),
        migrations.AddField(
            model_name='loaninformation',
            name='phone_no',
            field=models.CharField(default='017', max_length=20),
            preserve_default=False,
        ),
    ]
