# Generated by Django 5.0.3 on 2024-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0012_rename_remarks_loaninformation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninformation',
            name='balance_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loaninformation',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='balance_credit'),
        ),
        migrations.AlterField(
            model_name='tenderproject',
            name='job_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tender No'),
        ),
    ]
